<?php

/**
 * @file
 * Contains first_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function first_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the first_block module.
    case 'help.page.first_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
  function first_block_theme($existing, $type, $theme, $path) {
  // return array(
  //   'first_block' => array(
  //     'variables'=> array('name' => '')
  //   )
  // );
  return [
    'first_block' => [
      'variables' => ['test_var' => NULL],
    ],
  ];
}
}
