<?php

/**
 * @file
 * Contains ap_task94.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 *
 * Implements hook_preprocess_maintenance_page()
 */

function ap_task94_preprocess_maintenance_page(&$variables) {
  $variables['#attached']['library'][] = 'ap_task94/my_library';
}
/**
 * Implements hook_theme().
 */

function ap_task94_theme($existing, $type, $theme, $path )
{
  return [
    'current_date' => [
      'variables' => ['message' => NULL],
      'path' => drupal_get_path('module', 'ap_task94') . '/templates',
    ],
  ];

}

