<?php

/**
 * @file
 * Contains test_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function test_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the test_block module.
    case 'help.page.test_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
  function test_block_theme($existing, $type, $theme, $path) {
    return [
      'default_block' => [
        'variables' => ['test_var' => NULL],
      ],
    ];
  }

}
