<?php

/**
 * @file
 * Contains ap_task97.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_preprocess_page().
 */
 function ap_task97_preprocess_page (&$variables) {
    $logged_in = \ Drupal :: currentUser () -> isAuthenticated ();
    if (! $logged_in) {
      $libraries ['# attached'] ['library'] [] = 'core / drupal.ajax';
      $libraries ['# attached'] ['library'] [] = 'core / drupal.dialog.ajax';
       render ($libraries);
           }
         }
